serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12345
  path: /people

loggerConfig:
  outputDir: ./logs/
  outputFile: people.log

databaseConfig:
  dbUsername: root
  dbPassword: "1234"
  dbHostname: localhost
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: peopledb
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST